# Generated by Django 4.2.6 on 2023-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='converted_url',
            field=models.URLField(default='https://doi.org/10.1109/5.771073'),
        ),
        migrations.AddField(
            model_name='post',
            name='original_string',
            field=models.CharField(default='10.1109/5.771073', max_length=255),
        ),
    ]
