# Generated by Django 4.2.6 on 2023-10-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_post_converted_url_post_original_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='converted_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='original_string',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='10.1093/ajae/aaq063'),
        ),
    ]
